version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/uninexushr
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - uninexus-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uninexushr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - uninexus-network

volumes:
  postgres_data:

networks:
  uninexus-network:
    driver: bridge
