"""add_invited_by_to_invitations

Revision ID: 79539c1736f4
Revises: 41ab16c275ff
Create Date: 2024-12-18 12:19:50.533619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79539c1736f4'
down_revision: Union[str, None] = '41ab16c275ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('invitations', 'is_accepted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('is_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invitations', 'status')
    # ### end Alembic commands ###
